import { Hono } from "hono";
import { healthCheck } from "@/helpers";
import { quizRouter, submissionRouter } from "@/modules/assessments";
import { authRouter } from "@/modules/auth";
import { aiTutorRouter } from "@/modules/ai-tutor";
import { certificateRouter } from "@/modules/certificates";
import { reviewRouter } from "@/modules/reviews";
import { studentRouter } from "@/modules/student";
import { adminRouter } from "@/modules/admin";
import { communityRouter, memberRouter } from "@/modules/communities";
import { courseRouter, moduleRouter } from "@/modules/courses";
import { enrollmentRouter } from "@/modules/enrollments";
import { earningsRouter } from "@/modules/earnings";
import { instructorRouter } from "@/modules/instructor";
import { messagingRouter } from "@/modules/messaging";
import { notificationRouter } from "@/modules/notifications";
import { searchRouter } from "@/modules/search";
import { paymentRouter, instructorWithdrawalRouter, adminWithdrawalRouter } from "@/modules/payment";
import { testRouter } from "@/modules/test";
import { uploadRouter } from "@/modules/upload";
import { userRouter } from "@/modules/user/user.routes";
import { webhookRouter } from "./webhook.routes";

export const router = new Hono();

router.get("/", healthCheck);

router.route("/auth", authRouter);
router.route("/courses", aiTutorRouter);
router.route("/certificates", certificateRouter);
router.route("/reviews", reviewRouter);
router.route("/student", studentRouter);
router.route("/admin", adminRouter);
router.route("/communities", communityRouter);
router.route("/courses", courseRouter);
router.route("/enrollments", enrollmentRouter);
router.route("/instructor/earnings", earningsRouter);
router.route("/instructor", instructorRouter);
router.route("/messages", messagingRouter);
router.route("/members", memberRouter);
router.route("/modules", moduleRouter);
router.route("/quiz", quizRouter);
router.route("/submissions", submissionRouter);
router.route("/test", testRouter);
router.route("/payment", paymentRouter);
router.route("/notifications", notificationRouter);
router.route("/search", searchRouter);
router.route("/instructor/withdrawals", instructorWithdrawalRouter);
router.route("/admin/withdrawals", adminWithdrawalRouter);
router.route("/upload", uploadRouter);
router.route("/user", userRouter);
router.route("/webhook", webhookRouter);
