/**
 * @info - Centralised table-name constants.
 *         Use these everywhere instead of raw strings so renames are a single edit.
 */
export enum TableNames {
	USERS = "users",
	USER_ROLES = "user_roles",
	INSTRUCTOR_PROFILES = "instructor_profiles",
	STUDENT_PROFILES = "student_profiles",
	PARENT_PROFILES = "parent_profiles",
	PARENT_CHILD_LINKS = "parent_child_links",
	COMMUNITIES = "communities",
	COMMUNITY_MEMBERS = "community_members",
	COMMUNITY_INVITES = "community_invites",
	COMMUNITY_POSTS = "community_posts",
	COMMUNITY_POST_ATTACHMENTS = "community_post_attachments",
	COMMUNITY_POST_LIKES = "community_post_likes",
	COMMUNITY_POST_COMMENTS = "community_post_comments",
	COURSES = "courses",
	MODULES = "modules",
	LESSONS = "lessons",
	QUIZ_QUESTIONS = "quiz_questions",
	QUIZ_ATTEMPTS = "quiz_attempts",
	ASSIGNMENT_SUBMISSIONS = "assignment_submissions",
	ENROLLMENTS = "enrollments",
	LESSON_PROGRESS = "lesson_progress",
	PAYMENTS = "payments",
	WITHDRAWALS = "withdrawals",
	INSTRUCTOR_BALANCES = "instructor_balances",
	INSTRUCTOR_TRANSACTIONS = "instructor_transactions",
	REVIEWS = "reviews",
	COMMUNITY_RATINGS = "community_ratings",
	INSTRUCTOR_REPLIES = "instructor_replies",
	CERTIFICATES = "certificates",
	CONVERSATIONS = "conversations",
	CONVERSATION_PARTICIPANTS = "conversation_participants",
	MESSAGES = "messages",
	NOTIFICATIONS = "notifications",
	USER_CREDENTIALS = "user_credentials",
	LESSON_CHUNKS = "lesson_chunks",
	AI_TUTOR_LOGS = "ai_tutor_logs",
}
